hmcts/rpx-xui-approve-org

Jenkinsfile_CNP

Adding jenkins cnp file

---

yarn.lock

Updating yarn lock file

---

Dockerfile
docker/buildrun-docker-base.sh
docker/compose/docker-compose-ccd.yml
docker/compose/docker-compose-dm.yml
docker/compose/docker-compose-em.yml
docker/compose/docker-compose-idam.yml
docker/docker-compose-base-ports.yml
docker/docker-compose-base.yml

Adding docker file

---

sonar-project.properties

Adding sonar file

---

angular.json

Updating json

---

charts/xui-approve-org/values.template.yaml
infrastructure/main.tf

Approve org

---

package-lock.json
package.json
yarn.lock

updating lock files

---

config/application.config.ts
config/environments/aat.config.ts
config/environments/demo.config.ts
config/environments/docker.config.ts
config/environments/local.config.ts
config/environments/mock.config.ts
config/environments/preview.config.ts
config/environments/prod.config.js
config/environments/prod.config.ts
config/environments/saat.config.ts
config/environments/spreview.config.ts
config/environments/sprod.config.ts
config/index.ts
config/run-mutation-tests.sh

add config files

---

package.json

updating package lock

---

src/org-pending/containers/index.ts
src/org-pending/containers/org-success/org-approval-success.component.html
src/org-pending/containers/org-success/org-approval-success.component.spec.ts
src/org-pending/containers/org-success/org-approval-success.component.ts
src/org-pending/org-pending.ts

Adding the Success files

---

charts/xuiao-webapp/Chart.yaml
charts/xuiao-webapp/requirements.yaml
charts/xuiao-webapp/values.aat.template.yaml
charts/xuiao-webapp/values.template.yaml

Adding charts

---

src/org-manager/components/notification-banner/notification-banner.component.html
src/org-manager/containers/overview/org-overview.component.html
src/org-manager/containers/overview/org-overview.component.ts

EUI-301/Bug fix

---

.gitignore
package.json
test/e2e/config/conf.js
test/e2e/config/crossbrowser.conf.js
test/e2e/config/functional.conf.js
test/e2e/config/protractor.conf.js
test/e2e/config/smoke.conf.js
test/e2e/features/app/approveOrganisationBanner.feature
test/e2e/features/pageObjects/approveOrganisationObjects.js
test/e2e/features/pageObjects/dummyObjects.steps.js
test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
test/e2e/features/step_definitions/steps/dummy.steps.js
test/e2e/support/config.js
test/e2e/support/constants.js
test/e2e/support/hooks.js
test/e2e/support/reports.js
test/e2e/support/tagProcessor.js
test/e2e/support/timeout.js
test/e2e/support/world.js
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-282
https://tools.hmcts.net/jira/browse/EUI-188
Added Automation Framework to XUI Approve Organisation repo and added test for banner checking organisations
```
[x ] Yes
[ ] No
```

automation framework and banner test added

---

test/e2e/config/conf.js
test/e2e/features/app/confirmApproveOrganisation.feature
test/e2e/features/pageObjects/approveOrganisationObjects.js
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js

https://tools.hmcts.net/jira/browse/EUI-187
Added Automation Tests
```
[ ] Yes
[x ] No
```

EUI-187-ApproveOrganisation

---

src/app/containers/header/header.component.ts
test/e2e/config/conf.js
test/e2e/config/smoke.conf.js
test/e2e/features/app/reviewApproveOrganisation.feature
test/e2e/features/pageObjects/approveOrganisationObjects.js
test/e2e/features/step_definitions/steps/reviewApproveOrganisation.steps.js

https://tools.hmcts.net/jira/browse/EUI-198
https://tools.hmcts.net/jira/browse/EUI-301
Automation tests added and EUI 309 bug fixed.
```
[ ] Yes
[ x] No
```

EUI-309_bugfix_EUI-198_test_automation

---

README.md
package.json
whitelist.sh

Whitelisting 

---

api/server.ts
proxy.config.json

fix proxy add auth call back to pipeline

---

api/server.ts

routes are moved

---

api/auth/index.ts
api/lib/appInsights.ts
config/index.ts
iisnode.yml

Chore/proxy + missing callback

---

api/lib/config/environments/local.config.ts

update local config

---

src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
src/org-manager/containers/overview-pending/pending-overview.component.spec.ts
src/org-manager/containers/overview-pending/pending-overview.component.ts
src/org-manager/mock/pending-organisation.mock.ts

EUI-260 fixed issues around test and reverted .input in html

---

src/app/app.routes.ts
src/org-manager/org-manager.routing.ts

https://tools.hmcts.net/jira/browse/EUI-361
Fixed bug
```
[ ] Yes
[x] No
```

EUI-361 fixed canactivate issue

---

src/org-manager/store/effects/organisation.effects.ts

Fix for build error

---

src/org-manager/components/summary-pending/summary-pending.component.html
src/org-manager/components/summary-pending/summary-pending.component.spec.ts
src/org-manager/components/summary-pending/summary-pending.component.ts
src/org-manager/containers/overview-pending/pending-overview.component.ts
src/org-manager/store/reducers/org-pending.reducer.ts
src/org-manager/store/selectors/organisation.selectors.ts

Pending Organisation overview

---

test/e2e/config/conf.js
test/e2e/features/app/approveOrganisationBanner.feature
test/e2e/features/app/confirmApproveOrganisation.feature
test/e2e/features/app/loginLogout.feature
test/e2e/features/app/reviewApproveOrganisation.feature
test/e2e/features/pageObjects/dummyObjects.steps.js
test/e2e/features/pageObjects/headerPage.js
test/e2e/features/pageObjects/loginLogoutPage.js
test/e2e/features/step_definitions/steps/dummy.steps.js
test/e2e/features/step_definitions/steps/loginLogout.steps.js

Eui 389 log inand log out automation

---

src/org-manager/components/summary-pending/summary-pending.component.html
src/org-manager/components/summary/summary.component.html

https://tools.hmcts.net/jira/browse/EUI-436
```
[ ] Yes
[ x] No
```

fixed typo EUI 436

---

src/app/containers/header/header.component.html
src/shared/components/phase-banner/phase-banner.component.html
src/shared/components/phase-banner/phase-banner.component.ts
src/shared/shared.module.ts

https://tools.hmcts.net/jira/browse/EUI-213
Added component
```
[ ] Yes
[x] No
```

EUI-213 added component

---

test/e2e/config/conf.js
test/e2e/features/app/loginLogout.feature
test/e2e/features/pageObjects/headerPage.js
test/e2e/features/pageObjects/loginLogoutObjects.js
test/e2e/features/step_definitions/steps/loginLogout.steps.js

Added the LoginandLogoutAutiomation test

---

src/org-manager/containers/org-success/org-approval-success.component.html
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js

https://tools.hmcts.net/jira/browse/EUI-440
```
[ ] Yes
[ x] No
```

typo errors fixed EUI-440

---

src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
src/org-manager/containers/org-pending-approve/org-pending-approve.component.ts
src/org-manager/containers/org-success/org-approval-success.component.html
src/org-manager/containers/overview-pending/pending-overview.component.ts
src/org-manager/store/actions/org-pending.actions.ts
src/org-manager/store/effects/org-pending-effects.spec.ts
src/org-manager/store/effects/org-pending.effects.ts
src/org-manager/store/reducers/org-pending.reducer.ts
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js

Resolves EUI-257
Implements an error message for server errors on approve step

Approve organisation server error message

---

src/app/utils/app-utils.spec.ts
src/app/utils/app-utils.ts
src/org-manager/models/organisation.ts
src/org-manager/services/pending-organisation.service.spec.ts
src/org-manager/store/effects/org-pending.effects.ts
src/org-manager/store/effects/organisation.effects.ts
src/org-manager/store/reducers/org-pending.reducer.ts

undefined fix

---

src/app/app.module.ts

EUI-368 Disable redux dev tools in prod

---

src/app/app.module.ts

Updating variable

---

src/org-manager/containers/org-pending-approve/org-pending-approve.component.html

Missing email fix

---

src/services/auth/auth.service.ts

url redirect adding scope

---

README.md

Update README.md title as per feedback from DevOps

---

api/auth/index.ts
api/lib/config/application.config.ts
api/lib/config/environments/local.config.ts
api/organisation/index.ts
src/environments/environment.ts
src/services/auth/auth.service.ts

chaning endpoint to preview

---

api/services/serviceAuth.ts
src/app/store/effects/app.effects.ts

https://tools.hmcts.net/jira/browse/EUI-518
Removal of front end cookie removal
```
[ ] Yes
[x] No
```

EUI-518 getting rid of front end cookie removal

---

api/lib/config/environments/demo.config.ts
api/lib/config/environments/local.config.ts

add idam login urls to node config

add idam login urls to node config

---

src/app/app.module.ts
src/org-manager/store/effects/org-pending.effects.ts
src/org-manager/store/effects/organisation.effects.ts
src/org-manager/store/effects/single-org-pending.effects.ts
src/org-manager/store/effects/single-org.effects.ts
src/shared/errorHandler/defaultErrorHandler.spec.ts
src/shared/errorHandler/defaultErrorHandler.ts

commenting out the logger service to try

---

api/auth/serviceToken.ts

missing default function for s2sToken generation

---

api/services/serviceAuth.ts

Add the logging info for the error

---

api/auth/index.ts

Fix for security bug login refresh

---

infrastructure/main.tf

added env var
```
[ ] Yes
[x ] No
```

added env var

---

api/lib/config/environments/local.config.ts
api/organisation/index.ts
src/app/utils/app-utils.ts
src/environments/environment.prod.ts
src/environments/environment.ts
src/org-manager/components/summary/summary.component.html
src/org-manager/components/summary/summary.component.ts
src/org-manager/services/organisation.service.ts
src/org-manager/store/actions/single-org.actions.spec.ts
src/org-manager/store/actions/single-org.actions.ts
src/org-manager/store/effects/single-org.effects.spec.ts
src/org-manager/store/effects/single-org.effects.ts
src/org-manager/store/reducers/single-org.reducer.spec.ts

Refactor, clean up and make the approve Org details work

---

src/app/app.constants.ts
src/app/app.routes.ts
src/app/components/hmcts-global-footer/hmcts-global-footer.component.html
src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts
src/app/containers/cookie-policy/cookie-policy.component.html
src/app/containers/cookie-policy/cookie-policy.component.ts
src/app/containers/index.ts
src/app/containers/privacy-policy/privacy-policy.component.html
src/app/containers/privacy-policy/privacy-policy.component.ts
src/app/containers/terms-and-conditions/terms-and-conditions.component.html
src/app/containers/terms-and-conditions/terms-and-conditions.component.ts

https://tools.hmcts.net/jira/browse/EUI-460
https://tools.hmcts.net/jira/browse/EUI-461
https://tools.hmcts.net/jira/browse/EUI-218
All changes done
```
[ ] Yes
[x] No
```

Cookie policy. Privacy Policy and T&C's pages

---

src/app/app.module.ts
src/org-manager/store/effects/org-pending.effects.ts
src/org-manager/store/effects/organisation.effects.ts
src/shared/errorHandler/defaultErrorHandler.spec.ts
src/shared/errorHandler/defaultErrorHandler.ts
src/shared/shared.module.ts

Adding Logger/Appinsights/Default error Handler back now

---

src/app/containers/footer/footer.component.ts

adding comment

---

api/server.ts

Adding the missing APPINSIGHTS_INSTRUMENTATION key

---

api/auth/index.ts
src/services/auth/auth.service.ts

add extra roles

---

api/lib/appInsights.ts
api/lib/log4jui.ts
api/local.ts

Adding logging for Appinsights not working

---

api/lib/appInsights.ts

Incorrect environment variable PUI_ENV

---

src/org-manager/components/summary-pending/summary-pending.component.html

changing pending badge from green to blue

---

src/shared/components/phase-banner/phase-banner.component.html

adding feedback link

---

infrastructure/aat.tfvars

https://tools.hmcts.net/jira/browse/EUI-843
introduced a new env variable to see if this is put into the vault/app in aat only.
```
[ ] Yes
[x] No
```

testing to see if variable is deployed to key vault

---

src/app/components/privacy-policy/privacy-policy.component.spec.ts

Adding test for privacy policy

---

src/app/components/accessibility/accessibility.component.html
src/app/components/cookie-policy/cookie-policy.component.html
src/app/components/privacy-policy/privacy-policy.component.html
src/app/components/terms-and-conditions/terms-and-conditions.component.html
src/assets/sass/components/_cookie-banner.scss
src/org-manager/components/summary-pending/summary-pending.component.html
src/org-manager/components/summary/summary.component.html
src/org-manager/containers/org-pending-approve/org-pending-approve.component.html
src/org-manager/containers/org-success/org-approval-success.component.html
src/org-manager/containers/overview-pending/pending-overview.component.html
src/shared/components/identity-bar/identity-bar.component.html

fixing the container width to 1220px

---

Jenkinsfile_CNP

disable production deployment

---

src/app/app.constants.ts
src/app/utils/app-utils.ts

https://tools.hmcts.net/jira/browse/EUI-987
```
[ ] Yes
[x] No
```

perftest config added

---

Jenkinsfile_CNP

Disable pact

---

Dockerfile
api/lib/config/environments/preview.config.ts
api/local.ts
api/routes.ts
charts/xui-ao-webapp/values.aat.template.yaml
charts/xui-ao-webapp/values.preview.template.yaml
infrastructure/main.tf
infrastructure/variables.tf
whitelist.sh

Enable PR envs

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
charts/xui-ao-webapp/values.yaml
infrastructure/main.tf

seperate s2s & idam to different KV secret

---

infrastructure/variables.tf

Fixed incompatible terraform variables.tf
```
[ ] Yes
[ ] No
```

fixed terraform variables

---

api/lib/environment.config.ts
api/lib/tunnel.ts
api/server.ts

added logging for debug

---

infrastructure/main.tf
infrastructure/variables.tf

removed PORT references from terraform

---

src/app/components/accessibility/accessibility.component.html
src/app/components/accessibility/accessibility.component.ts

making both date the same

---

Jenkinsfile_CNP
charts/xui-ao-webapp/Chart.yaml

upgarde helm client version

---

infrastructure/ithc.tfvars

added terraform file for ithc

---

api/lib/interceptors.ts

added error checking around error interceptor

---

tslint.json

Mark new and changed rules as warning only

---

src/org-manager/containers/organisation-details/organisation-details.component.html
src/org-manager/org-manager.routing.ts

adding pba code in

---

src/org-manager/containers/active-organisations/active-organisations.component.html
src/org-manager/containers/organisation-details/organisation-details.component.html
src/org-manager/containers/organisation-details/organisation-details.component.spec.ts
src/org-manager/containers/organisation-details/organisation-details.component.ts
src/org-manager/containers/pending-organisations/pending-organisations.component.html
src/org-manager/containers/pending-organisations/pending-organisations.component.ts
src/org-manager/store/effects/organisation-effects.spec.ts
src/org-manager/store/effects/organisation.effects.ts
src/org-manager/store/reducers/organisation.reducer.spec.ts
src/org-manager/store/reducers/organisation.reducer.ts
test/e2e/features/app/confirmApproveOrganisation.feature
test/e2e/features/app/search.feature
test/e2e/features/pageObjects/organisationListPage.js
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
test/e2e/features/step_definitions/steps/searchOrganisations.steps.js
test/e2e/support/customWaits.js

work for EUI-1372, EUI-1412 and EUI-1415

---

src/org-manager/containers/organisation-details/organisation-details.component.html
yarn.lock

make sure there wont be any empty account name

---

src/org-manager/containers/approve-organisation/approve-organisation.component.html

adding the missing postcode

---

Jenkinsfile_CNP
api/.env.defaults
api/local.ts
api/server.ts
charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.preview.template.yaml
infrastructure/aat.tfvars
package.json
yarn.lock

Feature/health endpoint ithc v2 

---

Jenkinsfile_CNP
api/local.ts
api/server.ts
charts/xui-ao-webapp/Chart.yaml
package.json
yarn.lock

added health endpoint for all services

---

Jenkinsfile_CNP

disable      enableDockerBuild()
```
[ ] Yes
[ ] No
```

disable      enableDockerBuild()

---

infrastructure/main.tf
infrastructure/variables.tf

added new env variable for node config

---

api/lib/appInsights.ts
api/local.ts
charts/xui-ao-webapp/values.aat.template.yaml
charts/xui-ao-webapp/values.preview.template.yaml
config/custom-environment-variables.json

missing references when mount point not available

---

api/lib/appInsights.ts
api/local.ts
charts/xui-ao-webapp/values.aat.template.yaml
charts/xui-ao-webapp/values.preview.template.yaml
config/custom-environment-variables.json

missing references when mount point not available (#248)

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.aat.template.yaml
charts/xui-ao-webapp/values.yaml

incorrect urls for idam

---

Jenkinsfile_CNP

promote to AAT only

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.yaml

Update ITHC IDAM url
```
[ ] Yes
[ ] No
```

Update ITHC IDAM url

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.yaml

update idam url

---

api/health.ts
api/local.ts
api/server.ts

added health endpoint

---

src/org-manager/containers/approve-organisation/approve-organisation.component.html
test/e2e/config/conf.js
test/e2e/features/app/approveOrganisationBanner.feature
test/e2e/features/app/confirmApproveOrganisation.feature
test/e2e/features/app/reviewApproveOrganisation.feature
test/e2e/features/pageObjects/approveOrganisationObjects.js
test/e2e/features/pageObjects/organisationListPage.js
test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
test/e2e/features/step_definitions/steps/loginLogout.steps.js
test/e2e/features/step_definitions/steps/searchOrganisations.steps.js
test/e2e/support/customWaits.js

Functions test merged from master for missing changes

---

infrastructure/ithc.tfvars

updating IDAM URLS to non AKS
```
[ ] Yes
[ ] No
```

updating IDAM URLS to non AKS

---

README.md
api/application.ts
api/auth/index.ts
api/auth/userRoleAuth.ts
api/configuration/constants.ts
api/configuration/index.ts
api/lib/models/index.ts
api/lib/objectUtilities.ts
package.json
src/services/auth/auth.service.ts
yarn.lock

Application.ts with api/auth changes

---

Jenkinsfile_CNP
Jenkinsfile_parameterized
api/lib/appInsights.ts
charts/xui-ao-webapp/values.yaml
config/custom-environment-variables.json

appinsights key changes

---

api/configuration/references.ts
charts/xui-ao-webapp/Chart.yaml

Master to develop

---

api/application.ts

remove secrets from Log

---

api/application.ts

removing APP_INSIGHTS_KEY

---

api/application.ts
api/lib/sessionStore.ts
package.json
yarn.lock

Adding the application and session with health check

---

src/polyfills.ts

https://tools.hmcts.net/jira/browse/EUI-921
Polyfills
```
[ ] Yes
[x] No
```

EUI-921 polyfills

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/requirements.yaml

update bitnami chart

---

src/app/components/accessibility/accessibility.component.html

Accessibility text changes.

---

Jenkinsfile_CNP
Jenkinsfile_nightly

Added Jenkins nightly for full functional tests

---

charts/xui-ao-webapp/Chart.yaml

updating charts

---

test/e2e/features/app/organisationUserReadAccess.feature
test/e2e/features/pageObjects/organisationPage.js
test/e2e/support/hooks.js

Fix functional tests.

---

infrastructure/main.tf
infrastructure/variables.tf

ASE env cleanup

---

charts/xui-ao-webapp/values.preview.template.yaml
src/org-manager/components/back-link/back-link.component.ts

Back button bug fix - resolves eui-1845

Back button bug fix eui-1845

---

src/app/containers/header/header.component.ts
test/e2e/features/step_definitions/steps/loginLogout.steps.js

Chnaged the header

---

Jenkinsfile_nightly
security.sh

ZAP security test enable
```
[ ] Yes
[ x] No
```

ZAP security tests for AO

---

stryker.node.conf.js

fixed missing stryker config file.

---

package.json
src/app/components/signed-out/signed-out.component.html
src/app/containers/app/app.component.html
src/styles.scss
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2081
Restyle modal dialog buttons to match styling used in Manage Organisations application.
```
[ ] Yes
[x] No
```

EUI-2081: Timeout modal dialog styling change

---

api/user/index.ts

https://tools.hmcts.net/jira/browse/EUI-2081
Set timeout to a fixed value of 10 minutes for now.
```
[ ] Yes
[x] No
```

EUI-2081: Hard-coded modal dialog timeout

---

charts/xui-ao-webapp/values.preview.template.yaml

fix new preview

---

src/org-manager/containers/organisation-details/organisation-details.component.ts

bug to fix the users/Organisation state

---

.github/stale.yml

add stalebot for AO

---

yarn.lock

Master to develop 2214 2

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

add AO App Insights for ITHC

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

add app insghts

---

test/e2e/features/pageObjects/organisationListPage.js
test/e2e/features/step_definitions/steps/loginLogout.steps.js

Fix to handle EUI-1856 login.

---

Jenkinsfile_CNP
api/.env.defaults
api/application.ts
package.json
yarn.lock

update session key xui-approve-org and also upgrade xui-node-lib

---

Jenkinsfile_nightly
security.sh
test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
test/e2e/features/step_definitions/steps/loginLogout.steps.js
test/e2e/support/CucumberReporter.js
test/e2e/support/customWaits.js
test/e2e/support/hooks.js

tests/hooks async attach screenshot fix.

---

src/app/utils/app-utils.spec.ts
src/app/utils/app-utils.ts

Eui 1804 enhance coverage rate 2

---

test/e2e/config/crossbrowser.conf.js
test/e2e/features/app/loginLogout.feature

EUI_3026_IE11Otherbrowsers_support

---

package.json
src/app/app.routes.ts
src/app/containers/redirect/redirect.component.spec.ts
src/app/containers/redirect/redirect.component.ts
src/org-manager/org-manager.routing.ts
yarn.lock

Bug/e UI 3103 role guard

---

api/caseWorkerDetailsRouter/index.ts
api/caseWorkerDetailsRouter/mock-error-scenarios.ts
src/case-worker-ref-data/case-worker-ref-data.routing.ts
src/case-worker-ref-data/components/case-worker-details/case-worker-details.component.spec.ts
src/case-worker-ref-data/components/case-worker-details/case-worker-details.component.ts
src/case-worker-ref-data/components/index.ts
src/case-worker-ref-data/components/upload-info-details/upload-info-details.component.html
src/case-worker-ref-data/components/upload-info-details/upload-info-details.component.ts
src/case-worker-ref-data/components/upload-info-partial-success/upload-info-partial-success.html
src/case-worker-ref-data/components/upload-info-partial-success/upload-info-partial-success.ts
src/case-worker-ref-data/models/case-worker-ref-data.model.ts

Feature/e UI 3023 partial success

---

src/app/components/privacy-policy/privacy-policy.component.html

https://tools.hmcts.net/jira/browse/EUI-3058
Update the address and add email to the 'Your rights' section under 'Overview', and update the address in the section 'You can contact the MoJ data protection officer by'
```
[ ] Yes
[x] No
```

Update postal and email address in Privacy policy

---

projects/gov-ui/src/lib/gov-ui.module.ts
src/app/app.constants.ts
src/caseworker-ref-data/components/caseworker-details/caseworker-details.component.html
src/caseworker-ref-data/components/upload-info-details/upload-info-details.component.html
src/caseworker-ref-data/components/upload-info-partial-success/upload-info-partial-success.html

https://tools.hmcts.net/jira/browse/EUI-3230
Content changes from Caseworker to Staff
```
[ ] Yes
[ x] No
```

Feature/e UI 3230 content changes

---

Jenkinsfile_nightly
README.md
charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/requirements.yaml
test/e2e/config/crossbrowser.conf.js

https://tools.hmcts.net/jira/browse/EUI-3391
Upgrade to helm chart api version v2
```
[ ] Yes
[x] No
```

helm api upgrade

---

charts/xui-ao-webapp/Chart.yaml

downgrade node chart version

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.yaml

Xui disable autoscaling

---

Jenkinsfile_CNP
api/test/pact/pact-tests/idam/getUserDetails.spec.ts
api/test/pact/pact-tests/rdProfessional/getOrganisations.spec.ts
package.json

Ta-229: Fix failing RD and Idam Pact test

---

charts/xui-ao-webapp/Chart.yaml

https://tools.hmcts.net/jira/browse/EUI-4342
Upgrade nodejs base chart to latest version

upgrade nodejs chart to 2.3.7

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/EUI-4388
Add syncBranchesWithMaster to Jenkins config
```
[ ] Yes
[x] No
```

Add syncBranchesWithMaster to Jenkins config

---

src/org-manager/components/organisation-details-info/organisation-details-info.component.html

https://tools.hmcts.net/jira/browse/EUI-2133
extra heading to be implemented to describe purpose of the screen
```
[ ] Yes
[x] No
```

EUI-2133 Non-descriptive Headings

---

package.json
src/assets/sass/patterns/_pba.scss
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2135
Imported latest gov frontend
```
[ ] Yes
[x] No
```

EUI-2135 imported latest gov frontend

---

Jenkinsfile_CNP
package.json
src/app/app.constants.ts
src/app/app.module.ts
src/assets/sass/patterns/_pba.scss
src/caseworker-ref-data/caseworker-ref-data.module.ts
src/org-manager/components/organisation-details-info/organisation-details-info.component.html
src/org-manager/org-manager.module.ts
src/shared/shared.module.ts
test/e2e/config/fullfunctional.conf.js
test/e2e/features/app/deleteActiveOrganisation.feature
test/e2e/features/pageObjects/approveOrganisationObjects.js
test/e2e/features/pageObjects/organisationListPage.js
test/e2e/features/step_definitions/steps/approveOrganisation.steps.js
test/e2e/features/step_definitions/steps/confirmApproveOrganisation.steps.js
test/ngIntegration/util/browserUtil.js
yarn.lock

https://tools.hmcts.net/jira/browse/EUI-2133
https://tools.hmcts.net/jira/browse/EUI-2135
https://tools.hmcts.net/jira/browse/EUI-3802
https://tools.hmcts.net/jira/browse/EUI-4288
EXUI_AO_4.0.25 Release
```
[ ] Yes
[x] No
```

EXUI_AO_4.0.25_Release

---

src/caseworker-ref-data/components/caseworker-details/caseworker-details.component.html

https://tools.hmcts.net/jira/browse/EUI-4786
Minor change to template link
```
[ ] Yes
[ x] No
```

fix template link

---

test/accessibility/config/protractor.conf.js
test/accessibility/helpers/pa11yUtil.js

Master build test enhancement with retry logic. 
PR raised as part of release support.
Master build test enhancement with retry logic.
```
[ ] Yes
[ x] No
```

a11y test retry on error

---

charts/xui-ao-webapp/Chart.yaml

https://tools.hmcts.net/jira/browse/EUI-5273
Upgrade node base chart to 2.4.0
```
[ ] Yes
[x] No
```

Upgrade node base chart to 2.4.0

---

src/org-manager/containers/home/home.component.html
src/org-manager/containers/home/home.component.ts
src/org-manager/containers/review-organisation/review-organisation.component.html
src/org-manager/containers/review-organisation/review-organisation.component.ts
src/org-manager/services/pending-organisation.service.spec.ts
src/org-manager/services/pending-organisation.service.ts
src/org-manager/store/actions/organisations.actions.spec.ts
src/org-manager/store/actions/organisations.actions.ts
src/org-manager/store/effects/organisation.effects.spec.ts
src/org-manager/store/effects/organisation.effects.ts
src/org-manager/store/reducers/organisation.reducer.spec.ts
src/org-manager/store/reducers/organisation.reducer.ts

https://tools.hmcts.net/jira/browse/EUI-3726
AO | Click on Confirm on Confirm your decision page -New registrations( Multiple PBA's)- Happy Path
```
[ ] Yes
[X] No
```

Feature/e UI 3726 new registrations happy path

---

api/organisation/index.ts
api/updatePba/index.ts
api/updatePba/routes.ts
src/app/utils/app-utils.ts
src/caseworker-ref-data/components/caseworker-details/caseworker-details.component.ts
src/caseworker-ref-data/utils/caseworker-utils.spec.ts
src/enums/sort-order.ts
src/models/common/sort-field.model.ts
src/models/dtos/index.ts
src/org-manager/containers/active-organisations/active-organisations.component.html
src/org-manager/containers/active-organisations/active-organisations.component.spec.ts
src/org-manager/containers/active-organisations/active-organisations.component.ts
src/org-manager/containers/delete-organisation-success/delete-organisation-success.component.spec.ts
src/org-manager/containers/home/home.component.html
src/org-manager/containers/home/home.component.spec.ts
src/org-manager/containers/home/home.component.ts
src/org-manager/containers/organisation-list/organisation-list.component.ts
src/org-manager/containers/pending-organisations/pending-organisations.component.html
src/org-manager/containers/pending-organisations/pending-organisations.component.spec.ts
src/org-manager/containers/pending-organisations/pending-organisations.component.ts
src/org-manager/containers/pending-pbas/pending-pbas.component.html
src/org-manager/containers/pending-pbas/pending-pbas.component.spec.ts
src/org-manager/containers/pending-pbas/pending-pbas.component.ts
src/org-manager/services/organisation.service.ts
src/org-manager/services/pba.service.ts
src/org-manager/services/pending-organisation.service.spec.ts
src/shared/utils/handle-fatal-errors.ts

https://tools.hmcts.net/jira/browse/EUI-4053
https://tools.hmcts.net/jira/browse/EUI-5178
Load New Registrations, New PBA's and Active Organisations tabs from API instead of NGRX Store. Add spinner functionality during loading.
```
[ ] Yes
[x] No
```

Load Organisation Tabs including spinner

---

src/org-manager/components/index.ts
src/org-manager/components/organisation-details-info/organisation-details-info.component.html
src/org-manager/components/organisation-details-info/organisation-details-info.component.spec.ts
src/org-manager/components/quick-links/quick-links.component.html
src/org-manager/components/quick-links/quick-links.component.spec.ts
src/org-manager/components/quick-links/quick-links.component.ts
src/org-manager/components/quick-links/quick-links.scss

https://tools.hmcts.net/jira/browse/EUI-3678
Add quick link functionality to pending organisations and organisations that are under review
```
[ ] Yes
[x] No
```

Quick link functionality

---

src/app/containers/app/app.component.ts
src/org-manager/components/organisation-details-info/organisation-details-info.component.html
src/org-manager/containers/approve-organisation/approve-organisation.component.ts
src/org-manager/containers/delete-organisation/delete-organisation.component.spec.ts
src/org-manager/containers/delete-organisation/delete-organisation.component.ts
src/org-manager/containers/edit-details/edit-details.component.html
src/org-manager/containers/organisation-details/organisation-details.component.ts
src/org-manager/containers/pending-pbas/pending-pbas.component.html
src/org-manager/containers/review-organisation/review-organisation.component.spec.ts
src/org-manager/containers/review-organisation/review-organisation.component.ts
src/org-manager/services/organisation.service.ts
src/services/auth/auth.guard.ts

https://tools.hmcts.net/jira/browse/EUI-4339
```
[ ] Yes
[ x] No
```

E UI 4339 intergrate with pba add remove

---

stryker.node.conf.js

[EUI-6241](https://tools.hmcts.net/jira/browse/EUI-6241)
Mutation Config File template modification after upgrade to Angular 11.
```
[ ] Yes
[x] No
```
**Log after run
```
Ran all tests for this mutant.
Ran 10.97 tests per mutant on average.
--------------------------|---------|----------|-----------|------------|----------|---------|
File                      | % score | # killed | # timeout | # survived | # no cov | # error |
--------------------------|---------|----------|-----------|------------|----------|---------|
All files                 |    0.47 |        7 |         0 |       1470 | …
```

Mutation Config File template modification after upgrade to Angular 11.

---

src/app/utils/app-utils.spec.ts

Improve test coverage
```
[ ] Yes
[x] No
```

Improve test coverage

---

test/integration/config/environments/preview.config.ts
whitelist.sh

https://tools.hmcts.net/jira/browse/EXUI-208
Migrate .internal to platform.hmcts.net domain
```
[ ] Yes
[x] No
```

EXUI-208 Migrate .internal url

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.yaml

https://tools.hmcts.net/jira/browse/EXUI-268
Point to new Redis V6 instance
```
[ ] Yes
[x] No
```

EXUI-268 Step 2: Point to Redis V6 instance

---

src/app/app.module.ts

https://tools.hmcts.net/jira/browse/EXUI-852
NullInjectorError: No provider for i! error fix
- [] Does this PR introduce a breaking change

EXUI-852: NullInjectorError: R3InjectorError(ut)[i -> i -> i]:

---

api/test/pact/pact-tests/s2s/postToS2S.spec.ts

https://tools.hmcts.net/jira/browse/EUI-9092

pact test update

---

infrastructure/main.tf
infrastructure/provider.tf

https://tools.hmcts.net/jira/browse/CME-321
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)

CME-321: Upgrade azurerm

---

package.json

https://tools.hmcts.net/jira/browse/EXUI-2853
Cross browser test failure

exui-2853-revert the change

---

charts/xui-ao-webapp/Chart.yaml
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/CME-385
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

CME-385: OCI Images

---

infrastructure/main.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/CME-495
Update terraform to create app insights connection string

CME-495 update terraform to create app insights connection string

---

package.json
yarn.lock

See [EXUI-3339](https://tools.hmcts.net/jira/browse/EXUI-3339)
Fix for critical CVE, updated form-data from v ^3.0.0 to ^4.0.4

EXUI-3339 - Fix CVE vulnerability in AO - form-data

---

package.json

remove a11y step from pipeline

remove a11y from functional step

---

charts/xui-ao-webapp/Chart.yaml
charts/xui-ao-webapp/values.yaml

https://tools.hmcts.net/jira/browse/EXUI-3542
Fix bitnami AKS deploy issue
Should resolve as MC did
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
* [ x ] No

EXUI-3542 - Fix bitnami issue
